### ISSUE TITLE
srsUE cannot connect to COTS eNB which sends SIB6. 

### ISSUE THREAD

**Issue by DancingSW** [srsran/srsRAN#1097] opened 2023-02-12 21:00 UTC
## Issue Description ##
I am trying to connect srsUE to COTS eNB (baicells).

**1) srsUE can connect to srsENB when I use two SDRs.**
**2) When srsUE tries to connect to COTS eNB, it fails to connect and receives the "RRC connection release" as follows:**

> Random Access Transmission: seq=7, tti=3211, ra-rnti=0x2
> Random Access Complete.     c-rnti=0x33, ta=5
> RRC Connected
> Received RRC Connection Release (releaseCause: loadBalancingTAUrequired)
> RRC IDLE
> Attach failed (attempt 1/5)

**3) In the ue log file, I found that the COTS eNB sends SIB6, and the srsUE does not support SIB6.**

> 2023-02-12T20:27:09.115257 [RRC    ] [I] Processing SIB3 (1/3)
> 2023-02-12T20:27:09.115258 [PHY    ] [I] [ 3200] Setting new PHY configuration cc_idx=0...
> 2023-02-12T20:27:09.115258 [RRC    ] [I] SIB3 received
> 2023-02-12T20:27:09.115258 [RRC    ] [I] Processing SIB6 (2/3)
> 2023-02-12T20:27:09.115258 [RRC    ] [W] SIB6 is not supported
> 2023-02-12T20:27:09.115259 [PHY    ] [I] [ 3200] PRACH: cell.id=1, configIdx=3, rootSequence=1, zeroCorrelationConfig=1, freqOffset=0
> 2023-02-12T20:27:09.115512 [PHY    ] [I] [ 3200] Finished setting new PRACH configuration.
> 

I briefly looked over the srsUE source code and could not find any functions related to SIB6.
Is this problem caused because srsUE does not support SIB6?

## Setup Details ##
OS: Ubuntu 22.04
SDR: BladeRF Micro A4
COST eNB: Baicells FDD eNB

## Expected Behavior ##
srsUE can connect to the COTS eNB.

## Actual Behaviour ##
srsUE receives the RRC connection release and fails to connect. 

## Steps to reproduce the problem ##
Looked over srsUE source code, but could not find the functions related to SIB6.

## Additional Information ##
COTS eNB is connected to Open5GS core (MME).
I increased the RRC inactive time of the COTS eNB.
[ue_mac.pcap](https://drive.google.com/file/d/1Flx60fyVt2WnIrYGbSjy93kUchp4P_P_/view?usp=sharing)
[ue.log](https://drive.google.com/file/d/1h7jWkNhBfdLI5gLRM3Re8BA48_Z21VfH/view?usp=share_link)

**Comment by andrepuschmann** [comment] 2023-02-13 09:12
Hey, you receive a connection release after a successful RRC Setup. It has nothing to do with SIB6. Check your eNB logs to find the cause. Closing this issue.

**Closed by andrepuschmann** 2023-02-13 09:12 UTC
