### ISSUE TITLE
5G SA End to End using Open5GS and srsRAN with ZMQ -  Failed to setup/configure GW interface when start srsue

### ISSUE THREAD

**Issue by Edgard21031969** [srsran/srsRAN#981] opened 2022-09-05 17:45 UTC
## Issue Description ##
[I used the link https://docs.srsran.com/en/hoverxref_test/app_notes/source/5g_sa_E2E/source/index.html to simulate the 5G SA network.]

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[The connection should be successfully established once the UE has been assigned an IP address]

## Actual Behaviour ##
[When I launch srsenb and srsue, they started. But after, I have on ue the following error : Failed to setup/configure GW interface
RRC Connected
Failed to setup/configure GW interface
RRC NR reconfiguration successful
Received RRC Release
]

## Steps to reproduce the problem ##
[I reproduce the same configuration as showing on the link: ue.conf, rr.conf, enb.conf, amf.yaml, upf.yaml] 
<img width="719" alt="Capture-srsenb" src="https://user-images.githubusercontent.com/48598007/188496691-7c1c87e7-a922-48f9-831f-43b859ca0e41.PNG">
<img width="714" alt="Capture-srsue" src="https://user-images.githubusercontent.com/48598007/188496728-3c8a4cd8-4e11-417a-91c4-2a2006476954.PNG">

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by robertfalkenberg** [comment] 2022-09-19 12:58
The UE needs permission to spawn a `tun` network device. The easiest way is to run the application as `root` via `sudo`.

**Comment by robertfalkenberg** [comment] 2022-09-19 13:14
Another option is to configure the capabilities for the `srsue` binary

```
sudo setcap cap_net_admin+eip <...>/build/srsue/src/srsue
```
after each build.

**Comment by andrepuschmann** [comment] 2022-09-21 07:50
Closing this after @robertfalkenberg provided the solution.

**Closed by andrepuschmann** 2022-09-21 07:50 UTC

**Comment by chaohwa4** [comment] 2023-03-24 15:34
After running as a root or using sudo, I still have the Failed to setup/configure GW interface issue from the UE hosted by a Ubutu 20.04 laptop.

**Comment by stadekawa** [comment] 2023-04-01 01:16
Make sure you created the network namespace.
`sudo ip netns add ue1`

**Comment by stadekawa** [comment] 2023-04-01 01:40
Make sure you created the network namespace.

`sudo ip netns add ue1`

**Comment by walidouaali** [comment] 2025-09-01 09:38
a common issue is caused by not isolating the UE network. To fix this, simply create a network namespace for the UE by running: 
sudo ip netns add ue1
