### ISSUE TITLE
MME Pooling or Multiple MME

### ISSUE THREAD

**Issue by NeilJohnR** [srsran/srsRAN#959] opened 2022-08-16 01:50 UTC
We're running an Commercial EPC--> enodeB --> SDR (b210) --> duplexer --> antenna . A complete set-up for a box base station. SRSENB 21.10 ; UHD 3.15.0

Can we able to point enodeb (srsneb) to multiple mme or mme pooling? in order to try or test the scenarios for voicecalls and sms, if it is working on srs, what is our adjustment we need to do?

**Comment by andrepuschmann** [comment] 2022-09-21 08:52
Closing, duplicate of https://github.com/srsran/srsRAN/issues/958

**Closed by andrepuschmann** 2022-09-21 08:52 UTC
